---
title: "Data Import"
author: "CC"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

#never use absolute paths; use relative paths instead

##load litters data

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

##load pups data

```{r}
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
pups_data

tail(pups_data)
skimr::skim(pups_data)
```

##play with column parsing

```{r}
litters_data = read_csv(
  file = "./data_import_examples/FAS_litters.csv")
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
view(litters_data)
```

##Read in an excel file...

```{r}
mlb11_data = read_excel(path = "./data_import_examples/mlb11.xlsx")
view(mlb11_data)
```


##Read in SAS

```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")
view(pulse_data)
```

##Import datasets

```{r}
library(tidyverse)
litters_data = read_csv("./data_import_examples/FAS_litters.csv",
  col_types = "ccddiiii")
  litters_data = janitor::clean_names(litters_data)
pups_data = read_csv("./data_import_examples/FAS_pups.csv",
  col_types = "ciiiii")
  pups_data = janitor::clean_names(pups_data)
```

##Selecting

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())
#those two variables shifted to be the first 2 columns, then all other variables follow

select(litters_data, -group)
#removing a column

select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP = group, litter_number)
#changing variable names

rename(litters_data, GROUP = group)
```

##Filtering !!!!!

```{r}
filter(litters_data, group == "Con7")
# == lgoical operator that asks a question and returns either a true or false type of answer. So group should only be Con7 in this scenario. Are these two things equal to each other? i.e. are there times when group variable is equal to Con7. Group wasn't actually assigned to be equal to Con7.

filter(litters_data, group == "Mod8")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

#filter(litters_data, group == "Con7" | group == "Mod8") This is another way to perform the "or" function, but below is the best option.
filter(litters_data, group %in% c("Con7", "Mod8"))

filter(litters_data, gd0_weight + gd18_weight < 70)
#addition of variables, less than, greater than certain values

drop_na(litters_data)
#drop na in any line of any variable
drop_na(litters_data, gd0_weight)
#drop na in specific variable
```

##Mutate

```{r}
mutate(
  litters_data,
  we_gain = gd18_weight - gd0_weight,
  #make new variable base on existing
  group = str_to_lower(group))
  #overwrite existing variables in dataset
```

##Arrange

```{r}
arrange(litters_data, pups_born_alive)
#ordered the dataset according to the number of pups born alive

arrange(litters_data, desc(pups_born_alive))
#arrange descending

arrange(litters_data, pups_born_alive, gd0_weight)
#first arranges by pups born alive variable, then if you have multiple pups with the same number in that variable, it will then arrange by gd0_weight
```

