---
title: "Data Import"
author: "CC"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

#never use absolute paths; use relative paths instead

##load litters data

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

##load pups data

```{r}
pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
pups_data

tail(pups_data)
skimr::skim(pups_data)
```

##play with column parsing

```{r}
litters_data = read_csv(
  file = "./data_import_examples/FAS_litters.csv")
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
view(litters_data)
```

##Read in an excel file...

```{r}
mlb11_data = read_excel(path = "./data_import_examples/mlb11.xlsx")
view(mlb11_data)
```


##Read in SAS

```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")
view(pulse_data)
```

